### PR TITLE
Patch automatically fixable vulnerabilities in monitor-scale app

### PR DESCRIPTION
**Pull request by thisgeek**
Used `npm audit fix` to run the updates, which produced the following
report:

```
+ express@4.16.4
+ body-parser@1.18.3
+ request@2.88.0
added 6 packages from 4 contributors, removed 5 packages, updated 28 packages and moved 1 package in 3.081s
fixed 13 of 31 vulnerabilities in 353 scanned packages
  2 package updates for 18 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```

Related to KC-163

### CODE REVIEW

**Comment by thisgeek** [comment]
@evan-kenzan I noticed the packages in dependency manifest for the monitor-scale application were all pinned to a specific version, i.e. you didn't use ranges. This change would introduce ranges where there were none before.

**Comment by evan-kenzan** [comment]
Do you need to update the yarn lock too?

**Comment by thisgeek** [comment]
> Do you need to update the yarn lock too?

I ran the install (with yarn 1.15.2) but nothing about the yarn.lock changed. I run it again just now, though, and I noticed the install failed. So I'll close this and see about that.

**Comment by thisgeek** [comment]
@evan-kenzan Installation in my dev environment was tripped up by the issue fixed in #114.

**Pull request closed without merging**
